//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_AppleBar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppleBar_dbEntities : DbContext
    {
        public AppleBar_dbEntities()
            : base("name=AppleBar_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppleRecycle_IPad> AppleRecycle_IPad { get; set; }
        public virtual DbSet<AppleRecycle_IPhone> AppleRecycle_IPhone { get; set; }
        public virtual DbSet<AppleRecycle_Mac> AppleRecycle_Mac { get; set; }
        public virtual DbSet<Navigation> Navigation { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<RepairCase_IPad> RepairCase_IPad { get; set; }
        public virtual DbSet<RepairCase_IPhone> RepairCase_IPhone { get; set; }
        public virtual DbSet<RepairePriceInfo_Board> RepairePriceInfo_Board { get; set; }
        public virtual DbSet<RepairePriceInfo_HomeDelivery> RepairePriceInfo_HomeDelivery { get; set; }
        public virtual DbSet<RepairePriceInfo_Mac> RepairePriceInfo_Mac { get; set; }
        public virtual DbSet<RepairPriceInfo_IPhone> RepairPriceInfo_IPhone { get; set; }
        public virtual DbSet<RrpairCase_Board> RrpairCase_Board { get; set; }
        public virtual DbSet<IPhoneRepair_BatteryRepaire> IPhoneRepair_BatteryRepaire { get; set; }
        public virtual DbSet<IPhoneRepair_BoardRepair> IPhoneRepair_BoardRepair { get; set; }
        public virtual DbSet<IPhoneRepair_SoakingRepair> IPhoneRepair_SoakingRepair { get; set; }
        public virtual DbSet<MacBookRepair_SoakingRepair> MacBookRepair_SoakingRepair { get; set; }
        public virtual DbSet<SubNavigation> SubNavigation { get; set; }
    }
}
